using Content.Client._NC.Trade.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Content.Shared._NC.Trade.UiDto;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Trade.UI.Windows;

[GenerateTypedNameReferences]
public sealed partial class StoreStructuredMenu : DefaultWindow
{
    public StoreStructuredMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetBalance(int amount) => BalanceValue.Text = amount.ToString();

    public void PopulateBuyListings(IEnumerable<StoreListingData> data, IPrototypeManager protos)
    {
        BuyList.DisposeAllChildren();

        foreach (var d in data)
        {
            var ctrl = new NcStoreListingControl();
            ctrl.SetListing(Loc.GetString($"store-listing-name-{d.ProtoId}"), d.Price);
            BuyList.AddChild(ctrl);
        }
    }
}
