using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._NC.Trade.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcStoreListingControl : Control
{
    public NcStoreListingControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetListing(string name, int price)
    {
        NameLabel.Text = name;
        PriceLabel.Text = price.ToString();
    }
}
