using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;

namespace Content.Client._NC.Trade.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcStoreListingControl : Control
{
    /// <summary>Событие клика по кнопке "Купить"</summary>
    public event Action? OnBuyPressed;
    /// <summary>Событие клика по кнопке "Продать"</summary>
    public event Action? OnSellPressed;
    /// <summary>Событие клика по кнопке "Обменять"</summary>
    public event Action? OnExchangePressed;

    public NcStoreListingControl()
    {
        RobustXamlLoader.Load(this);

        BuyButton.OnPressed += _ => OnBuyPressed?.Invoke();
        SellButton.OnPressed += _ => OnSellPressed?.Invoke();
        ExchangeButton.OnPressed += _ => OnExchangePressed?.Invoke();
    }

    /// <summary>
    /// Установить название, цену, иконку, описание, показать нужную кнопку.
    /// </summary>
    public void SetListing(
        string name,
        int price,
        Texture? icon = null,
        string? description = null,
        ListingMode mode = ListingMode.Buy
    )
    {
        NameLabel.Text = name;
        PriceLabel.Text = price.ToString();
        Icon.Texture = icon;
        NameLabel.ToolTip = !string.IsNullOrEmpty(description) ? description : null;

        // Показ/скрытие кнопок по режиму
        BuyButton.Visible = mode == ListingMode.Buy;
        SellButton.Visible = mode == ListingMode.Sell;
        ExchangeButton.Visible = mode == ListingMode.Exchange;
    }

    public void SetBuyEnabled(bool enabled = true) => BuyButton.Disabled = !enabled;
    public void SetSellEnabled(bool enabled = true) => SellButton.Disabled = !enabled;
    public void SetExchangeEnabled(bool enabled = true) => ExchangeButton.Disabled = !enabled;

    public void SetHighlighted(bool highlighted) => Modulate = highlighted ? Color.FromHex("#fdf5a6") : Color.White;

    // Опциональное enum для режима отображения
    public enum ListingMode { Buy, Sell, Exchange }
}
