using Content.Shared._NC.Trader;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Trade;

[GenerateTypedNameReferences]
public sealed partial class TraderListingControl : Control
{
    public event Action? OnClick;

    public TraderListingControl(TraderListingData data, Texture texture)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        StoreItemName.Text = data.Name;
        StoreItemDescription.SetMessage(string.Empty);
        StoreItemTexture.Texture = texture;

        StoreItemBuyButton.Text = data.Category == TraderCategory.Sell ? "Продать" : "Купить";
        StoreItemBuyButton.OnPressed += _ => OnClick?.Invoke();
    }
}
